### DISCUSSION TITLE
A few locale and value combinations wrongly report `PluralCategory::Other`

### DISCUSSION THREAD

**Discussion by janhohenheim** [unicode-org/icu4x#3421] [Q&A] [answered]
The following code fails:
```rust
let pr = PluralRules::try_new_unstable(
    &icu_testdata::unstable(),
    &locale!("pl").into(),
    PluralRuleType::Cardinal,
)
.unwrap();
let result = pr.category_for(1_usize);
assert_eq!(result, PluralCategory::One);
```
This happens because the `result` returned is `PluralCategory::Other`. However, when I check the CLDR, it says this:
![image](https://github.com/unicode-org/icu4x/assets/9047632/80acfd34-fb56-4837-a5f8-43d41051a828)

Which leads me to believe that while `1.0_f64` might very well be `PluralCategory::Other`, `1_usize` should be `PluralCategory::One`. 
Am I missing something? Disclaimer: I don't speak any Polish, I'm simply porting some tests that used a different library and expected a `One` here.

**Comment by zbraniecki** [comment]
Thank you for the report. Investigating.

**Comment by janhohenheim** [comment]
Update: I ported some more of the tested plurals of [this test written in C#](https://github.com/YarnSpinnerTool/YarnSpinner/blob/main/YarnSpinner.Tests/LanguageTests.cs#L185-L265) to [my crate using icu](https://github.com/yarn-slinger/yarn-slinger/blob/runtime-tests-impl/crates/runtime/src/pluralization.rs#L106-L184) and many of them fail, reporting `PluralCategory::Other` instead of what the C# library expected. A quick glance at the CLDR table makes me think these are also reported wrong, e.g. for Icelandic `1_usize` is also `Other` despite the table clearly saying otherwise.
![image](https://github.com/unicode-org/icu4x/assets/9047632/2617d0a0-b7c2-458d-85de-5cc95d27241a)

I'm still unsure, did I misconfigure something here? My dependencies look like this:
```toml
[dependencies]
icu_plurals = { version = "1.2.0", features = ["std"] }
icu_locid = { version = "1.2.0", features = ["std"] }
icu_testdata = { version = "1.2.0", default-features = false, features = ["std", "icu_plurals"] }
icu_provider = { version = "1.2.0", features = ["std"] }
fixed_decimal = { version = "0.5.3", features = ["std", "ryu"] }

```
