### ISSUE TITLE
MissingLocale error when creating Collator from BlobDataProvider

### ISSUE THREAD

**Issue by ajtribick** [unicode-org/icu4x#3654]
Running on Ubuntu 23.04:

Cargo.toml
```toml
[package]
name = "icu4xtest"
version = "0.1.0"
edition = "2021"

[dependencies]
icu = { version = "1.2.0", features = ["serde"] }
icu_provider_blob = "1.2.0"
```

main.rs
```rust
use icu::collator::{Collator, CollatorOptions};
use icu::locid::locale;
use icu_provider_blob::BlobDataProvider;

static DATA: &[u8] = include_bytes!("loc_data.postcard");

fn main() {
    let locale = locale!("en_GB");

    let provider = BlobDataProvider::try_new_from_static_blob(DATA).unwrap();

    let options = CollatorOptions::new();
    let collator =
        Collator::try_new_with_buffer_provider(&provider, &locale.into(), options).unwrap();
}
```

icu4x-datagen command:
```sh
$ icu4x-datagen --version
icu4-datagen 1.2.5
$ icu4x-datagen --overwrite --keys all --locales full --format blob --out src/loc_data.postcard
```

Output:
```none
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Data(DataError { kind: MissingLocale, key: Some(DataKey{collator/meta@1}), str_context: None, silent: false })', src/main.rs:14:84
```

The above occurs for all locales I have tried so far. It also occurs if I pass the locale explicitly to icu4x-datagen. As a test, I also tried creating a `DateTimeFormatter` from the postcard file and this worked successfully, so seems specific to `Collator`.
