### ISSUE TITLE
Use docs.rs all-features in more places

### ISSUE THREAD

**Issue by sffc** [unicode-org/icu4x#716]
```toml
[package.metadata.docs.rs]
all-features = true
```

We should use that instead of putting the following in the docs tests:

```rust
//! # #[cfg(feature = "provider_serde")] {
//! // ...
//! # } // feature = "provider_serde"
```

CC @Manishearth
